import type { Lang } from "../shared/prompt";

export const COPY = {
  id: {
    welcome: "Satu foto ruangannya, dan benda-benda di sana bisa bicara untuknya.",
    pickPhoto: "Ambil / pilih foto ruangan",
    photoNote: "Foto dikirim sekali ke layanan AI untuk mencari benda, lalu hanya disimpan di perangkat ini.",
    looking: "Mencari benda…",
    spotsTitle: "Titik bicara",
    done: "Selesai",
    holdToEdit: "Tahan 2 detik untuk mengatur",
    hear: "Dengar",
    edit: "Ubah",
    remove: "Hapus",
    addSpot: "Tambah titik",
    addHint: "Ketuk foto tepat di bendanya.",
    phrasePlaceholder: "Contoh: Aku mau minum",
    save: "Simpan",
    cancel: "Batal",
    maxReached: "Sudah 12 titik — hapus satu untuk menambah.",
    langLocked: "Ganti foto untuk mengganti bahasa.",
    failed: "Belum berhasil mencari benda. Periksa internet, lalu coba lagi — atau tambahkan titik sendiri.",
    retry: "Coba lagi",
    nothingFound: "Belum ada benda yang jelas. Coba foto yang lebih terang dari sudut lain, atau tambahkan titik sendiri.",
    noVoice: "Perangkat ini belum punya suara Bahasa Indonesia. Kalimat akan tampil sebagai tulisan besar saat disentuh.",
    replaceTitle: "Ganti foto? Semua titik di foto ini akan dihapus.",
    replaceConfirm: "Ganti foto",
    replacePhoto: "Ganti foto",
    removed: "Titik dihapus.",
    undo: "Urungkan",
    coreLabel: "Kata dasar",
    handoffTitle: "Siap dipakai",
    handoffBody: "Sentuh benda di foto, dan perangkat akan bicara untuknya. Baris bawah selalu ada untuk kata dasar.",
    handoffWayBack: "Untuk mengatur lagi, tahan tombol di pojok kanan atas selama 2 detik.",
    handoffOk: "Mengerti",
    storageFailed: "Tidak bisa menyimpan di perangkat ini. Adegan tetap bisa dipakai sampai halaman ditutup. Ketuk Selesai lagi untuk lanjut.",
  },
  en: {
    welcome: "One photo of his room, and the things in it can speak for him.",
    pickPhoto: "Take / choose a room photo",
    photoNote: "The photo is sent once to an AI service to find objects, then kept only on this device.",
    looking: "Looking for objects…",
    spotsTitle: "Speaking spots",
    done: "Done",
    holdToEdit: "Hold 2 seconds to edit",
    hear: "Hear",
    edit: "Edit",
    remove: "Remove",
    addSpot: "Add spot",
    addHint: "Tap the photo right on the object.",
    phrasePlaceholder: "e.g. I'd like a drink",
    save: "Save",
    cancel: "Cancel",
    maxReached: "12 spots already — remove one to add another.",
    langLocked: "Choose a new photo to change the language.",
    failed: "Couldn't look for objects. Check the internet and try again — or add spots yourself.",
    retry: "Try again",
    nothingFound: "No clear objects found. Try a brighter photo from another angle, or add spots yourself.",
    noVoice: "This device has no English voice. Phrases will show as large text when tapped.",
    replaceTitle: "Replace the photo? All spots on this photo will be removed.",
    replaceConfirm: "Replace photo",
    replacePhoto: "Replace photo",
    removed: "Spot removed.",
    undo: "Undo",
    coreLabel: "Core words",
    handoffTitle: "Ready to use",
    handoffBody: "Touch something in the photo and the device speaks for him. The bottom row always has the core words.",
    handoffWayBack: "To edit again, hold the button in the top-right corner for 2 seconds.",
    handoffOk: "Got it",
    storageFailed: "Couldn't save on this device. The scene works until this page is closed. Tap Done again to continue.",
  },
} satisfies Record<Lang, Record<string, string>>;

export type Copy = (typeof COPY)["id"];

// Always-on core row: short label on the button, what gets spoken.
export const CORE_WORDS: Record<Lang, { label: string; phrase: string }[]> = {
  id: [
    { label: "Ya", phrase: "Ya" },
    { label: "Tidak", phrase: "Tidak" },
    { label: "Tolong", phrase: "Tolong" },
    { label: "Sakit", phrase: "Aku sakit" },
    { label: "Toilet", phrase: "Aku mau ke toilet" },
  ],
  en: [
    { label: "Yes", phrase: "Yes" },
    { label: "No", phrase: "No" },
    { label: "Help", phrase: "Help me" },
    { label: "Pain", phrase: "I'm in pain" },
    { label: "Toilet", phrase: "I need the toilet" },
  ],
};
